# Generated by Django 3.0.4 on 2024-03-07 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20200524_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\akash\\PycharmProjects\\Art-Gallery-Using-Django-master\\src\\media'),
        ),
        migrations.AlterField(
            model_name='mycart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 9, 43, 49, 533224)),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 9, 43, 49, 534225)),
        ),
    ]
