# Generated by Django 3.0.4 on 2024-03-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=200)),
                ('UserEmail', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
